### ISSUE TITLE
Improve default payment processor handling for User

### ISSUE THREAD

**Issue by barbaraliau** [Storj/service-storage-models#36]
Not necessary at the moment. Only have one payment processor. Add to the User model.

**Comment by barbaraliau** [comment]
- [ ] Add validation such that only one payment processor can be default
- [ ] Don't assume default when support multiple payment methods/processors (in `User.methods.addPaymentProcessor`)
- [ ] Make `adapter.register` support multiple payment processors
- [ ] Consider restructuring `.virtual('defaultCard')` to `.virtual('defaultPaymentMethod')`

```javascript
PaymentProcessor.virtual('defaultCard').get(function() {
  return this.adapter.defaultPaymentMethod(this);
});
```

**Comment by RichardLitt** [comment]
Stale.
