### ISSUE TITLE
Write herokuAdapter.register method

### ISSUE THREAD

**Issue by barbaraliau** [Storj/service-storage-models#39]
Notes: I think this is what we need from BitCore (https://bitcore.io/api/lib/public-key)
- [ ] find user, get user's public key
- [ ] verify using bitcore library
- [ ] make up a public key for now
- [ ]  service-integrations-public key
- [ ] signature = user's public key signed by the service-integration key

**Comment by braydonf** [comment]
FWIW: Once there are more numerous adapters, it will likely make sense to have billing specific functionality (communicating with payment processor APIs and necessary dependencies) to be included in the billing repo, instead of storage models.

**Comment by RichardLitt** [comment]
Stale.
