### ISSUE TITLE
PubKey model email validation

### ISSUE THREAD

**Issue by braydonf** [Storj/service-storage-models#53]
The public key email validation does not allow for emails such as `user+test@domain.net`, we should reuse the same email validation as the user model.

**Comment by dylanlott** [comment]
Waiting on some model and utils changes from @barbaraliau and then I'm going to fix this.

**Comment by braydonf** [comment]
@dylanlott went ahead and fixed this, since it was only a few lines after the refactor https://github.com/Storj/service-storage-models/pull/62/commits/de8bd875e45dd2018662ec05014ffadd1e583b93
