### ISSUE TITLE
Better log handling or alternative

### ISSUE THREAD

**Issue by braydonf** [Storj/service-storage-models#59]
We either need to have an ability to log using similar logging as the bridge here, or to raise specific errors and logging can be handled elsewhere. See balanceDebits in  lib/models/payment-processor-adapters/stripe.js

**Comment by dylanlott** [comment]
Do we want to look into a storj logger? I wrote a logger a little while back that just wrapped bunyan and added some storj specific configuration stuff. I just never did anything with it because it got pushed back on my to do list.

**Comment by RichardLitt** [comment]
Stale.
