### ISSUE TITLE
Wrong timeoutRate calculation

### ISSUE THREAD

**Issue by littleskunk** [Storj/service-storage-models#96]
I am online for 24 hours now but I have a timeoutRate of 11% (I was offline a few hours yesterday)
```
lastSeen	"2017-04-25T19:07:29.724Z"
lastTimeout	"2017-04-24T17:36:01.412Z"
timeoutRate	0.11701600694444443"
```

The problem is that timeoutRate is only updated on timeout. As long as I don't have any timeouts I am not able to get a better timeoutRate.

https://github.com/Storj/service-storage-models/blob/78b3fbd43969c565f98956dd9fff4d37a99f8ecc/lib/models/contact.js#L105-L110

Now I am offline for 3 hours and waiting for a timeout to get my 0% timeoutRate :/

**Comment by AlexeyALeonov** [comment]
My node was offline more than 5 hours, but timeoutRate never reset.
```
{"lastSeen":"2017-06-01T11:25:51.916Z","port":6000,"address":"188.242.148.175","userAgent":"6.5.0","protocol":"1.1.0","lastTimeout":"2017-05-19T13:30:25.579Z","timeoutRate":0.2199882060185185,"responseTime":4190.325135179835,"nodeID":"ef5d8f452ac2f015f9de3c0a0ab828e2c95ca99e"}
```

**Comment by ssa3512** [comment]
My nodes were offline for about a week due to a failed RAID array. Three are still showing timeoutRate of 1 even though they have been back online for a week and are functioning fine.
```
{"lastSeen":"2017-06-05T13:28:22.992Z","port":4004,"address":"storj3.ddns.net","userAgent":"6.5.0","protocol":"1.1.0","responseTime":677.728127837714,"lastTimeout":"2017-05-30T12:21:47.926Z","timeoutRate":1,"nodeID":"b86698d349fdb064e4228a441cdc31b74fc82e65"},
{"lastSeen":"2017-06-05T13:27:52.471Z","port":4008,"address":"storj3.ddns.net","userAgent":"6.5.0","protocol":"1.1.0","responseTime":564.4560756262978,"lastTimeout":"2017-05-29T12:17:46.005Z","timeoutRate":1,"nodeID":"b7d0cdcca39ea63c1d226d164ee8086ecc99c2db"}.
{"lastSeen":"2017-06-05T13:27:47.909Z","port":4000,"address":"storj3.ddns.net","userAgent":"6.5.0","protocol":"1.1.0","responseTime":692.7065127218293,"lastTimeout":"2017-05-30T03:21:55.868Z","timeoutRate":1,"nodeID":"e3caa9991833f159d11065b42f09a41b568418cd"},
{"lastSeen":"2017-06-05T13:27:32.067Z","port":4012,"address":"storj3.ddns.net","userAgent":"6.5.0","protocol":"1.1.0","responseTime":931.6882326064768,"lastTimeout":"2017-06-04T07:16:08.505Z","timeoutRate":0,"nodeID":"212e80de5e9ef0bcf6da4f0225b2118fce54db64"}
```

**Comment by treebeard** [comment]
`lastSeen: "2017-07-05T13:30:23.412Z"
lastTimeout: "2017-06-30T18:55:40.055Z"
timeoutRate: 0.012103854166666667`

My node was offline for a short time, but has been online for a few days without downtime. Also having this issue of timeout rate not resetting.

**Comment by ne0ark** [comment]
I am running into this as well. My nodes are stuck at the timeout that hasn't increased or decreased.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for logging this issue. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision here. This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this issue for now. If you have any questions, I encourage you to jump on RocketChat and ask them there. Thanks!
